version: "3.9"

services:
  app_blue:
    image: ${BLUE_IMAGE}
    container_name: stage-two-devops-app_blue
    environment:
      - PORT=3000
      - APP_POOL=blue
      - RELEASE_ID=${RELEASE_ID_BLUE}
    ports:
      - "8081:3000"
    restart: unless-stopped

  app_green:
    image: ${GREEN_IMAGE}
    container_name: stage-two-devops-app_green
    environment:
      - PORT=3000
      - APP_POOL=green
      - RELEASE_ID=${RELEASE_ID_GREEN}
    ports:
      - "8082:3000"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: stage-two-devops-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app_blue
      - app_green
    restart: unless-stopped
