version: "3.9"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "${PORT:-8080}:8080"
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/conf.d/default.conf.template:ro
    environment:
      ACTIVE_POOL: ${ACTIVE_POOL}
    command: /bin/sh -c "envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - app_blue
      - app_green

  app_blue:
    image: ${BLUE_IMAGE}
    environment:
      RELEASE_ID: ${RELEASE_ID_BLUE}
    ports:
      - "8081:3000"

  app_green:
    image: ${GREEN_IMAGE}
    environment:
      RELEASE_ID: ${RELEASE_ID_GREEN}
    ports:
      - "8082:3000"

